### ISSUE TITLE
nilJson naming issue in readme

### ISSUE THREAD

**Issue by ilyash-b** [otterize/nilable#1]
https://github.com/otterize/nilable/blob/9a144cdb7d0e547469da1c609f44c479c1ca325f/README.md?plain=1#L17

`nilJson` should be `nilable` or `nilableString` or alike. The `Json` part is wrong. `nilJson` is a data structure, not a string in JSON format.

**Comment by orishoshan** [comment]
Thanks @ilyash-b !
